apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nimbus-frontend-hpa
  namespace: nimbus
  labels:
    app.kubernetes.io/name: nimbus-frontend
    app.kubernetes.io/managed-by: argocd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nimbus-frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
