apiVersion: v1
kind: Secret
metadata:
  name: nimbus-rabbitmq-secret
  namespace: nimbus
  labels:
    app.kubernetes.io/name: nimbus-rabbitmq
    app.kubernetes.io/managed-by: argocd
type: Opaque
data:
  RABBITMQ_DEFAULT_PASS: bmltYnVzMTIz
