apiVersion: v1
kind: Service
metadata:
  name: nimbus-rabbitmq
  namespace: nimbus
  labels:
    app.kubernetes.io/name: nimbus-rabbitmq
    app.kubernetes.io/component: messaging
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nimbus-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
    - name: management
      port: 15672
      targetPort: management
      protocol: TCP
    - name: metrics
      port: 15692
      targetPort: metrics
      protocol: TCP
